### ISSUE TITLE
e is not defined

### ISSUE THREAD

**Issue by konnekkt** [torch2424/live-stream-radio#106] opened 2018-12-19 22:09 UTC
Hey first of all, thanks for your great work and sorry for my maybe bad english. Can you help me about this:

ReferenceError: e is not defined
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v8.14.1/lib/node_modules/live-stream-radio/src/index.js:117:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Best regards from Germany my friend.

**Comment by torch2424** [comment] 2018-12-20 00:50
@AndreasWebdev You speak German correct? Maybe you may be best to help out here if you have the time? 😄 

@konnekkt So after looking at the line it says to look at: https://github.com/torch2424/live-stream-radio/blob/master/src/index.js#L112

Seems like there is an error getting your `config.json`. Did you generate the project yourself, or perhaps try running everything in another directory? This is definitely a bug though, should have given a better error 😢

**Comment by konnekkt** [comment] 2018-12-20 08:51
Hi, thanks for your fast reply. I tried both, generating it by myself and using the standard. I also installed the ffmpeg 4.xx Version. Just something in my config seems to be wrong. After work i will try to get a better log. Best regards my friend

**Comment by torch2424** [comment] 2018-12-20 19:15
Sounds good! Yeah I think it may be the config, feel free to pass that along whenever you get the chance 😄

**Comment by AndreasWebdev** [comment] 2018-12-21 07:32
@torch2424 gonna write bi-lingual for reference purpose here :smile: 

@konnekkt Hey, am besten postet du die config.json hier rein, dann kann ich mir das mal anschauen. Achte darauf, deinen Stream-Key rauszunehmen um ihn nicht zu leaken. Wenn du dich mit Englisch schwer tust kannst du gerne auf Deutsch antworten, ich übersetze dann für's Protokoll ^^

_-> Hey, it would be the best if you could post the config.json here so I can take a look at it. Keep in mind to remove your stream-key so you don't leak it. If you have problems explaining your issue in English you can answer in German and I'll just translate it for everyone else ^^_

**Comment by konnekkt** [comment] 2018-12-21 11:58
Grüß dich Andreas, klar mache ich =) Danke schon mal für deine Hilfe!

[config.txt](https://github.com/torch2424/live-stream-radio/files/2702662/config.txt)

**Comment by AndreasWebdev** [comment] 2018-12-21 12:07
![image](https://user-images.githubusercontent.com/7365286/50341946-2982ac00-0521-11e9-974e-b9f79106fda3.png)

@torch2424 seems to be a normal config, json is valid, no special chars or anything.

@konnekkt kannst du prüfen, ob man die config json lesen und beschreiben kann? Vielleicht ist sie ja schreibgeschützt?

_> can you check if the config json is readable and writeable? Maybe file access to it is locked?_

**Comment by snibo13** [comment] 2018-12-22 00:04
For me, there was an issue with the pathname. A temporary solution would be putting the config.json file in a folder with the same name as your stream within the stream folder.

**Comment by snibo13** [comment] 2018-12-22 00:09
The issue is with the configJsonPath that is generated in the index. I'm working on a fix, but if anyone wants to try and beat me to it look around line 117.

**Comment by snibo13** [comment] 2018-12-22 00:32
Actually, I found a super simple fix. It gets appends a path to the present directory so just make sure you run the command from the root directory and it should work. You don't need to make any folders or modify the code.

**Comment by torch2424** [comment] 2018-12-22 00:54
@snibo13 Oh awesome! Thanks for proposing a fix! Yeah I need to go back and fix this to be more flexible with all the paths. But if it works, it works for now 😂

**Comment by AndreasWebdev** [comment] 2019-10-16 18:00
I'll close this issue for clarity, feel free to reopen it if you have any more questions :)

**Closed by AndreasWebdev** 2019-10-16 18:00 UTC
